### ISSUE TITLE
Error pytorch when building model

### ISSUE THREAD

**Issue by jeremycheminf** [xuhuihuang/featuredock#2]
Hello in commands, step3 to create models I get this error
```
Traceback (most recent call last):
  File "/home/jeremy/featuredock/src/models/train_main.py", line 269, in <module>
    run_one_fold(CONFIG['modelname'], [train_foldids, val_foldids, test_foldids], \
  File "/home/jeremy/featuredock/src/models/train_main.py", line 222, in run_one_fold
    stats = train_one_step(trainloader)
  File "/home/jeremy/featuredock/src/models/train_main.py", line 118, in train_one_step
    for x, y in dataloader:
  File "/home/jeremy/mambaforge/envs/featdock/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/jeremy/mambaforge/envs/featdock/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 672, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/jeremy/mambaforge/envs/featdock/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/jeremy/mambaforge/envs/featdock/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 288, in __iter__
    for idx in self.sampler:
  File "/home/jeremy/mambaforge/envs/featdock/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 239, in __iter__
    rand_tensor = torch.multinomial(self.weights, self.num_samples, self.replacement, generator=self.generator)
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)
```

Torch libraries are
torch               2.4.1
torchaudio          2.4.1
torchvision         0.19.1

I don't know if it's because I'm running out of memory on GPU

**Comment by jeremycheminf** [comment]
I was missing some files from step 2.
